backend/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('myapp.urls')),
    path("admin/", admin.site.urls),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/myapp/urls.py
from django.urls import path

from . import views

app_name = 'myapp'

urlpatterns = [
    path("", views.index, name="home"),
    #path("upload", views.image_upload, name="upload"),
    path("company_name", views.company_name, name="company_name"),

    # api endpoints
    path('api/save_company_name', views.SaveCompanyNameAPI.as_view(), name='save_company_name'),
]

backend/myapp/models.py
from django.db import models


# Create your models here.

class Company(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

backend/myapp/views.py
from django.shortcuts import render, HttpResponse
from django.core.files.storage import FileSystemStorage
from rest_framework.authentication import SessionAuthentication, BasicAuthentication, TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Company


def index(request):
    context = {}
    companies = Company.objects.all()
    if companies.count() > 0:
        company = companies.first()
        context["current_name"] = company.name
    else:
        context["current_name"] = "No Name Yet"
    return render(request, "index.html", context)


def company_name(request):
    name = "empty name"
    if request.method == "POST":
        name = request.POST.get("name").strip()
    return HttpResponse(name)


class SaveCompanyNameAPI(APIView):
    # authentication_classes = [SessionAuthentication, BasicAuthentication, TokenAuthentication]
    # permission_classes = [IsAuthenticated]

    def post(self, request):
        context = {}
        name = request.POST.get("name")
        companies = Company.objects.all()
        if companies.count() > 0:
            company = companies.first()
            company.name = name
            company.description = name
            company.save()
            context["status"] = "success"
            context["company_name"] = name
        else:
            company = Company()
            company.name = name
            company.description = name
            company.save()
            context["status"] = "success"
            context["company_name"] = name
        return Response(context)

    def get(self):
        context = {}
        name = "name is not defined!"
        companies = Company.objects.all()
        if companies.count() > 0:
            company = companies.first()
            name = company.name
        context["company_name"] = name
        return Response(context)

backend/myapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>

</head>
<body>

<div class="container mt-5">
    <div class="jumbotron">
        <strong><h1 class="display-4" id="company_name">{{current_name}}</h1></strong>
        <h4>Current Company Name:</h4>
        <form method="post" id="post-form">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" id="name" placeholder="Enter New Company Name" name="name">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <hr>
        <p>This is a simple ajax page created to test the company name change endpoint --<strong>api/save_company_name</strong></p>
    </div>
</div>
<script>
/*$(document).on('submit', '#post-form', function(e) {
    $.ajax({
        type: 'POST',
        url: '{% url "myapp:save_company_name" %}',
        data: {
            name: $('#name').val(),
            csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
            action: 'post'
        },
        success: function(json) {
            console.log("testtt");
            document.getElementById("company_name").html($('#name').val());
            document.getElementById("post-form").reset();
        },
        error: function(xhr, errmsg, err) {
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
    });
});*/

// this is the id of the form
$("#post-form").submit(function(e) {

    e.preventDefault(); // avoid to execute the actual submit of the form.

    var form = $(this);
    var actionUrl = form.attr('action');

    $.ajax({
        type: "POST",
        url: '{% url "myapp:save_company_name" %}',
        data: form.serialize(), // serializes the form's elements.
        success: function(data){
            console.log(data.company_name);
            document.getElementById("company_name").innerHTML = data.company_name;
        }
    });

});

</script>
</body>
</html>

backend/myapp/templates/upload.html
{% block content %}

  <form action="{% url 'myapp:upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="image_file">
    <input type="submit" value="submit" />
  </form>

  {% if image_url %}
    <p>File uploaded at: <a href="{{ image_url }}">{{ image_url }}</a></p>
  {% endif %}

{% endblock %}